bangpound_tag_search:
    path: /tag/search
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'BangpoundCastleSearchBundle:Static:search.html.twig'

bangpound_statistics:
    resource: "@BangpoundCastleSearchBundle/Controller/StatisticsController.php"
    type:     annotation
