parameters:
    bangpound_castle_search.controller.statistics.class: Bangpound\Bundle\CastleSearchBundle\Controller\StatisticsController

services:
    bangpound_castle_search.controller.statistics:
        class: %bangpound_castle_search.controller.statistics.class%
