parameters:
    rshief_migration.vbulletinpost.writer.class: Rshief\Bundle\MigrationBundle\Writer\DoctrineWriter

    rshief_migration.vbulletin_process_workflow.command.class: Rshief\Bundle\MigrationBundle\Command\VbulletinProcessWorkflowCommand

    rshief_migration.vbulletinpost.entity.class: Rshief\Bundle\MigrationBundle\Entity\VBulletinPost
    rshief_migration.vbulletinpost.reader.class: Rshief\Bundle\MigrationBundle\Reader\DoctrineReader
    rshief_migration.vbulletinpost.workflow.class: Ddeboer\DataImport\Workflow

    rshief_migration.collector_process_workflow.command.class: Rshief\Bundle\MigrationBundle\Command\CollectorProcessWorkflowCommand

    rshief_migration.collector.reader.class: Ddeboer\DataImport\Reader\DbalReader
    rshief_migration.collector.workflow.class: Ddeboer\DataImport\Workflow
    rshief_migration.collector.writer.class: Rshief\Bundle\MigrationBundle\Writer\DoctrineWriter

    rshief_migration.bbcode.converter.class: Decoda\Decoda
    rshief_migration.decoda.config:
        xhtmlOutput: true
        strictMode: false
        escapeHtml: true

services:
    rshief_migration.vbulletin_process_workflow.command:
        class: %rshief_migration.vbulletin_process_workflow.command.class%
        tags:
            - { name: console.command }

    rshief_migration.vbulletinpost.reader:
        class: %rshief_migration.vbulletinpost.reader.class%
        arguments: [ @doctrine.orm.entity_manager, %rshief_migration.vbulletinpost.entity.class% ]

    rshief_migration.vbulletinpost.workflow:
        class: %rshief_migration.vbulletinpost.workflow.class%
        arguments: [ @rshief_migration.vbulletinpost.reader ]
        calls:
            - [ "addWriter", [ @rshief_migration.vbulletinpost.writer ]]

    rshief_migration.vbulletinpost.writer:
        class: %rshief_migration.vbulletinpost.writer.class%
        arguments: [ @doctrine_couchdb.odm.document_manager, 'Rshief\Bundle\MigrationBundle\CouchDocument\AtomEntry', 'id' ]
        calls:
            - [ "disableTruncate", [] ]

    rshief_migration.collector_process_workflow.command:
        class: %rshief_migration.collector_process_workflow.command.class%
        tags:
            - { name: console.command }

    rshief_migration.collector.writer:
        class: %rshief_migration.collector.writer.class%
        arguments: [ @doctrine_couchdb.odm.document_manager, 'Rshief\Bundle\MigrationBundle\CouchDocument\CollectorAtomEntry', 'id' ]
        calls:
            - [ "disableTruncate", [] ]
            - [ setBatchSize, [ 1000 ]]

    rshief_migration.bbcode.converter:
        class: %rshief_migration.bbcode.converter.class%
        arguments: [ ]
