parameters:
    bangpound_atom_data.document.category.class: Bangpound\Atom\DataBundle\CouchDocument\CategoryType
    bangpound_atom_data.document.content.class: Bangpound\Atom\DataBundle\CouchDocument\ContentType
    bangpound_atom_data.document.entry.class: Bangpound\Atom\DataBundle\CouchDocument\EntryType
    bangpound_atom_data.document.feed.class: Bangpound\Atom\DataBundle\CouchDocument\FeedType
    bangpound_atom_data.document.generator.class: Bangpound\Atom\DataBundle\CouchDocument\GeneratorType
    bangpound_atom_data.document.link.class: Bangpound\Atom\DataBundle\CouchDocument\LinkType
    bangpound_atom_data.document.person.class: Bangpound\Atom\DataBundle\CouchDocument\PersonType
    bangpound_atom_data.document.source.class: Bangpound\Atom\DataBundle\CouchDocument\SourceType
    bangpound_atom_data.document.text.class: Bangpound\Atom\DataBundle\CouchDocument\TextType

services:
    bangpound_atom_data.normalizer.date_time:
        class: Bangpound\Atom\DataBundle\Serializer\DateTimeNormalizer
        tags:
            - { name: serializer.normalizer }
