parameters:
    rshief_migration.vbulletinpost.writer.class: Rshief\MigrationBundle\Writer\DoctrineWriter
    rshief_migration.process_workflow.command.class: Rshief\MigrationBundle\Command\ProcessWorkflowCommand
    rshief_migration.vbulletinpost.entity.class: Rshief\MigrationBundle\Entity\VBulletinPost
    rshief_migration.vbulletinpost.reader.class: Ddeboer\DataImport\Reader\DoctrineReader
    rshief_migration.vbulletinpost.workflow.class: Ddeboer\DataImport\Workflow
    rshief_migration.bbcode.converter.class: Decoda\Decoda
    rshief_migration.decoda.config:
        xhtmlOutput: true
        strictMode: false
        escapeHtml: true

services:
    rshief_migration.check.couchdb:
        class: Bangpound\Check\CouchDBCheck
        arguments: [ @doctrine_couchdb ]
        tags:
            - { name: liip_monitor.check }

    rshief_migration.process_workflow.command:
        class: %rshief_migration.process_workflow.command.class%
        tags:
            - { name: console.command }

    rshief_migration.vbulletinpost.reader:
        class: %rshief_migration.vbulletinpost.reader.class%
        arguments: [ @doctrine.orm.entity_manager, %rshief_migration.vbulletinpost.entity.class% ]

    rshief_migration.vbulletinpost.workflow:
        class: %rshief_migration.vbulletinpost.workflow.class%
        arguments: [ @rshief_migration.vbulletinpost.reader ]
        calls:
            - [ "addWriter", [ @rshief_migration.vbulletinpost.writer ]]

    rshief_migration.vbulletinpost.writer:
        class: %rshief_migration.vbulletinpost.writer.class%
        arguments: [ @doctrine_couchdb.odm.document_manager, %bangpound_atom_data.document.entry.class% ]
        calls:
            - [ "disableTruncate", [] ]

    rshief_migration.bbcode.converter:
        class: %rshief_migration.bbcode.converter.class%
        arguments: [ ]
