parameters:
    rshief_migration.enqueue.command.class: Rshief\MigrationBundle\Command\EnqueueCommand
    rshief_migration.to_couchdb.command.class: Rshief\MigrationBundle\Command\ToCouchDBCommand
    rshief_migration.process_workflow.command.class: Rshief\MigrationBundle\Command\ProcessWorkflowCommand
    rshief_migration.vbulletinpost.entity.class: Rshief\MigrationBundle\Entity\VBulletinPost
    rshief_migration.vbulletinpost.reader.class: Ddeboer\DataImport\Reader\DoctrineReader
    rshief_migration.vbulletinpost.workflow.class: Ddeboer\DataImport\Workflow
    rshief_migration.bbcode.converter.class: Decoda\Decoda
    rshief_migration.decoda.config:
        xhtmlOutput: true
        strictMode: false
        escapeHtml: true

services:
    rshief_migration.enqueue.command:
        class: %rshief_migration.enqueue.command.class%
        tags:
            - { name: console.command }

    rshief_migration.to_couchdb.command:
        class: %rshief_migration.to_couchdb.command.class%
        calls:
            - ["setClient", [ @doctrine_couchdb.client.default_connection ] ]
        tags:
            - { name: console.command }



    rshief_migration.process_workflow.command:
        class: %rshief_migration.process_workflow.command.class%
        tags:
            - { name: console.command }

    rshief_migration.vbulletinpost.reader:
        class: %rshief_migration.vbulletinpost.reader.class%
        arguments: [ @doctrine.orm.entity_manager, %rshief_migration.vbulletinpost.entity.class% ]

    rshief_migration.vbulletinpost.workflow:
        class: %rshief_migration.vbulletinpost.workflow.class%
        arguments: [ @rshief_migration.vbulletinpost.reader ]



    rshief_migration.bbcode.converter:
        class: %rshief_migration.bbcode.converter.class%
        arguments: [ ]
