parameters:
#    bangpound_castle.example.class: Bangpound\Bundle\CastleBundle\Example

services:
#    bangpound_castle.example:
#        class: %bangpound_castle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
