<?php

namespace AppBundle\Repository;

/**
 * StreamParametersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamParametersRepository extends \Doctrine\ORM\EntityRepository
{
}
