parameters:
    bangpound_atom_data.document.entry.class: Bangpound\Atom\DataBundle\CouchDocument\EntryType

services:
#    bangpound_atom_data.example:
#        class: %bangpound_atom_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
