imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: elasticsearch.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        castle_type_names: %bangpound_castle.types.lower%

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    polygon: Polygon
                    point: Point
            collector:
                driver:   pdo_mysql
                host:     %database_host%
                port:     %database_port%
                dbname:   rshief0_collector
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
        types:
            json:       Bangpound\Bundle\TwitterStreamingBundle\Types\JsonType
            Geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            Point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            Polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            LineString: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

old_sound_rabbit_mq:
    enable_collector: true
    connections:
        default:
            host:     %rabbitmq_host%
            user:     %rabbitmq_user%
            password: %rabbitmq_pass%
            port:     %rabbitmq_port%
            vhost:    %rabbitmq_vhost%
    producers:
        twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: direct }
            queue_options:    { name: 'twitter_stream', routing_keys: [ 'twitter_data.tweet' ] }
    consumers:
        twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: direct }
            queue_options:    { name: 'twitter_stream', routing_keys: [ 'twitter_data.tweet' ] }
            callback:         bangpound_twitter_streaming.consumer.notification

sensio_framework_extra:
    view: { annotations: false }

easy_admin:
    site_name: Castle
    entities:
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Follow
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Location
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Track

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

# Doctrine CouchDB Configuration
doctrine_couch_db:
    client:
        connections:
            default:
                dbname: %doctrine_couch_db.default.dbname%
                user: %doctrine_couch_db.default.user%
                password: %doctrine_couch_db.default.password%
            stats:
                dbname: %doctrine_couch_db.default.dbname%_stats
                user: %doctrine_couch_db.default.user%
                password: %doctrine_couch_db.default.password%

# Liip monitor
liip_monitor:
    enable_controller: true
    checks:
        php_extensions: [ intl, mcrypt, curl ]
        writable_directory:
            - %kernel.cache_dir%
            - %kernel.logs_dir%
        doctrine_dbal:            default
        symfony_version:          ~
        security_advisory:
            lock_file:            %kernel.root_dir%/../composer.lock
        http_service:
            couchdb:
                host:                 localhost
                port:                 5984
                path:                 /
            elasticsearch:
                host:                 %elasticsearch_host%
                port:                 %elasticsearch_port%
                path:                 /
        rabbit_mq:
            default:
                host:                 localhost
                port:                 5672
                user:                 guest
                password:             guest
                vhost:                /

bangpound_guzzle_proxy:
    endpoints:
        elasticsearch:
            base_url: http://%elasticsearch_host%:%elasticsearch_port%/%elasticsearch_index_name%/
        couchdb:
            base_url: http://127.0.0.1:5984/symfony

caxy_elasticsearch:
    client:
        default:
            hosts: [ %elasticsearch_host%:%elasticsearch_port% ]

fos_rest:
    param_fetcher_listener: force
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/doc', stop: true }
            - { path: '^/api', priorities: ['json'] }
            - { path: '^/', stop: true }
    view:
        view_response_listener:
            enabled: true

nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: ['Content-Type']
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/elasticsearch':
            allow_origin: ['*']
            allow_methods: ['GET', 'POST']
            max_age: 3600
        '^/tagstatistic/summary.json':
            allow_origin: ['*']
            allow_methods: ['GET']
            max_age: 3600

doctrine_cache:
    providers:
        statistics:
            type: file_system
            namespace: statistics
