imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: elasticsearch.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        packages:
            underscore_string_js:
                base_path: "bundles/bangpoundcastlesearch/components/underscore.string/dist/underscore.string.min.js"
            elasticsearch_angular_js:
                base_path: "bundles/bangpoundcastlesearch/components/elasticsearch/elasticsearch.angular.js"
            hinclude_js:
                base_path: "bundles/applicationassets/components/hinclude/hinclude.js"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        castle_type_names: %bangpound_castle.types.lower%

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    polygon: Polygon
                    point: Point
            collector:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   rshief0_collector
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
        types:
            json:       Bangpound\Bundle\TwitterStreamingBundle\Types\JsonType
            Geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            Point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            Polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            LineString: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            ApplicationUserBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

old_sound_rabbit_mq:
    enable_collector: true
    connections:
        default:
            host:     %rabbitmq_host%
            user:     %rabbitmq_user%
            password: %rabbitmq_pass%
            port:     %rabbitmq_port%
            vhost:    %rabbitmq_vhost%
    producers:
        twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: direct }
            queue_options:    { name: 'twitter_stream', routing_keys: [ 'twitter_data.tweet' ] }
    consumers:
        twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: direct }
            queue_options:    { name: 'twitter_stream', routing_keys: [ 'twitter_data.tweet' ] }
            callback:         bangpound_twitter_streaming.consumer.notification

easy_admin:
    site_name: Castle
    entities:
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Follow
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Location
        - Bangpound\Bundle\TwitterStreamingBundle\Entity\Track

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\UserBundle\Entity\User
    group:
        group_class: Application\UserBundle\Entity\Group

# Doctrine CouchDB Configuration
doctrine_couch_db:
    client:
        connections:
            default:
                dbname: %doctrine_couch_db.default.dbname%
                user: %doctrine_couch_db.default.user%
                password: %doctrine_couch_db.default.password%
            stats:
                dbname: %doctrine_couch_db.default.dbname%_stats
                user: %doctrine_couch_db.default.user%
                password: %doctrine_couch_db.default.password%
    odm:
        auto_mapping: true

# Liip monitor
liip_monitor:
    enable_controller: true
    checks:
        php_extensions: [ intl, mcrypt, curl ]
        writable_directory:
            - %kernel.cache_dir%
            - %kernel.logs_dir%
        doctrine_dbal:            default
        symfony_version:          ~
        security_advisory:
            lock_file:            %kernel.root_dir%/../composer.lock
        http_service:
            couchdb:
                host:                 localhost
                port:                 5984
                path:                 /
            elasticsearch:
                host:                 %elasticsearch_host%
                port:                 %elasticsearch_port%
                path:                 /
        rabbit_mq:
            default:
                host:                 localhost
                port:                 5672
                user:                 guest
                password:             guest
                vhost:                /

bangpound_guzzle_proxy:

caxy_elasticsearch:
    client:
        default:
            hosts: [ %elasticsearch_host%:%elasticsearch_port% ]

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        jsonp_handler: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/tagstatistic/summary.json':
            allow_origin: ['*']
            allow_methods: ['GET']
            max_age: 3600

doctrine_cache:
    providers:
        statistics:
            type: file_system
            namespace: statistics
