bangpound_elasticsearch:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        main:
            client: default
            index_name: production
            types:
                atom:
                    properties:
                        _attachments:
                            properties:
                                original:
                                    properties:
                                        content_type:
                                            type: string
                                        digest:
                                            type: string
                                        length:
                                            type: long
                                        revpos:
                                            type: long
                        _rev:
                            type: string
                        authors:
                            properties:
                                email:
                                    type: string
                                name:
                                    type: string
                                    index: not_analyzed
                                    omit_norms: true
                                    index_options: docs
                                uri:
                                    type: string
                        categories:
                            properties:
                                term:
                                    type: string
                                    index: not_analyzed
                                    omit_norms: true
                                    index_options: docs
                                scheme:
                                    type: string
                                label:
                                    type: string
                                type:
                                    type: string
                        content:
                            properties:
                                content:
                                    type: string
                                src:
                                    type: string
                                type:
                                    type: string
                        doctrine_metadata:
                            type: object
                            enabled: false
                        id:
                            type: string
                        links:
                            properties:
                                href:
                                    type: string
                                type:
                                    type: string
                                rel:
                                    type: string
                                title:
                                    type: string
                        published:
                            type: date
                            format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                            ignore_malformed: true
                        source:
                            properties:
                                authors:
                                    properties:
                                        email:
                                            type: string
                                        name:
                                            type: string
                                            index: not_analyzed
                                            omit_norms: true
                                            index_options: docs
                                        uri:
                                            type: string
                                categories:
                                    properties:
                                        term:
                                            type: string
                                            index: not_analyzed
                                        scheme:
                                            type: string
                                        label:
                                            type: string
                                id:
                                    type: string
                                links:
                                    properties:
                                        href:
                                            type: string
                                        type:
                                            type: string
                                        rel:
                                            type: string
                                        title:
                                            type: string
                                title:
                                    properties:
                                        text:
                                            type: string
                                            index: not_analyzed
                                            omit_norms: true
                                            index_options: docs
                                        type:
                                            type: string
                                type:
                                    type: string
                                updated:
                                    type: date
                                    format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                                    ignore_malformed: true
                        summary:
                            properties:
                                text:
                                    type: string
                                type:
                                    type: string
                        title:
                            properties:
                                text:
                                    type: string
                                type:
                                    type: string
                        type:
                            type: string
                        updated:
                            type: date
                            format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                            ignore_malformed: true
