ongr_elasticsearch:
    analysis:
        analyzer:
            tag_analyzer:
                filter:
                    - lowercase
                    - trim
                    - unique
                tokenizer: keyword
