app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

elasticsearch_proxy_search:
    path: /elasticsearch
    options:
        expose: true

bangpound_elasticsearch_proxy_search:
    type: guzzle_proxy
    resource: elasticsearch
    prefix: /elasticsearch
    options:
        expose: true

bangpound_couchdb_proxy:
    type: guzzle_proxy
    resource: couchdb
    prefix: /couchdb
    options:
        expose: true

root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /search
        permanent: true

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

_fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# app/config/routing.yml
YZSupervisorBundle:
    resource: "@YZSupervisorBundle/Resources/config/routing.xml"
    prefix: /admin/supervisor

stream_parameters:
    type:     rest
    resource: app.controller.collection_parameters_controller
    prefix: '/api'
    defaults: {_format: json}
    options:
        expose: true

rshief_kal3a_stats:
    resource: AppBundle\Controller\StatisticController
    type:     rest
    prefix: '/api'
    defaults: {_format: json}
    options:
        expose: true
