app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

elasticsearch_proxy_search:
    path: /elasticsearch
    options:
        expose: true

bangpound_elasticsearch_proxy_search:
    type: guzzle_proxy
    resource: elasticsearch
    prefix: /elasticsearch
    options:
        expose: true

bangpound_couchdb_proxy:
    type: guzzle_proxy
    resource: couchdb
    prefix: /couchdb
    options:
        expose: true

_fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# app/config/routing.yml
YZSupervisorBundle:
    resource: "@YZSupervisorBundle/Resources/config/routing.xml"
    prefix: /admin/supervisor

statistics_overview:
    path: /overview
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/overview.html.twig

_rest:
    resource: routing_rest.yml
    type: rest

_tag_stats_redirect:
    path: /tagstatistic/summary.json
    defaults:
        _controller: AppBundle:StreamParametersStatistics:getSummary
        parameters: 1
        _format: json

consul:
    prefix: /consul
    resource: '@ConsulBundle/Resources/config/routing.yml'
