rshief_kal3a:
    resource: "@RshiefKal3aBundle/Resources/config/routing.yml"

castle:
    resource: "@BangpoundCastleBundle/Resources/config/routing.yml"

bangpound_castle_search:
    resource: "@BangpoundCastleSearchBundle/Resources/config/routing.yml"

bangpound_elasticsearch_proxy:
    path: /elasticsearch/production
    options:
        expose: true

bangpound_elasticsearch_proxy_search:
    path: /elasticsearch/{path}
    requirements:
        path: 'production/_search'
    defaults:
        _controller: BangpoundGuzzleProxyBundle:Default:index
        endpoint: http://localhost:9200
        path: 'production/_search'
        _format: json
    methods: [GET,POST]

bangpound_couchdb_proxy:
    path: /couchdb/{path}
    requirements:
        path: '.+'
    defaults:
        _controller: BangpoundGuzzleProxyBundle:Default:index
        endpoint: http://localhost:5984
        _format: json
    methods: [GET]

root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /search
        permanent: true

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sputnik_pubsub_hub:
    resource: "@SputnikPubsubBundle/Resources/config/routing/hub.xml"
    prefix:   /hub

sputnik_pubsub_callback:
    resource: "@SputnikPubsubBundle/Resources/config/routing/callback.xml"
    prefix:   /push

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
