rshief_kal3a:
    resource: "@RshiefKal3aBundle/Resources/config/routing.yml"

castle:
    resource: "@BangpoundCastleBundle/Resources/config/routing.yml"

bangpound_castle_search:
    resource: "@BangpoundCastleSearchBundle/Resources/config/routing.yml"


bangpound_elasticsearch_proxy_search:
    type: guzzle_proxy
    resource: elasticsearch
    prefix: /elasticsearch/production
    options:
        expose: true

bangpound_couchdb_proxy:
    path: /couchdb/symfony/{path}
    requirements:
        path: '.+'
    defaults:
        _controller: BangpoundGuzzleProxyBundle:Default:index
        endpoint: http://127.0.0.1:5984/symfony
        _format: json
    methods: [GET]

root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /search
        permanent: true

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

_fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
