# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    # workaround for implicit dependency on PHP templating library.
    # see https://github.com/liip/LiipMonitorBundle/issues/125#issuecomment-220337440
    templating.helper.assets: '@assets.packages'
    templating.helper.router: '@router'

    check_couchdb:
        class: ZendDiagnostics\Check\CouchDBCheck
        arguments:
            -
                dbname: '%couchdb_name%'
                host: '%couchdb_host%'
                protocol: 'http'
                port: '%couchdb_port%'
                username: '%couchdb_user%'
                password: '%couchdb_password%'

        tags:
            - { name: liip_monitor.check, alias: couchdb }

    check_elasticsearch:
        class: ZendDiagnostics\Check\GuzzleHttpService
        arguments:
            - 'http://%elasticsearch_host%:%elasticsearch_port%/_cluster/health'
            - []
            - []
            - 200
            - status
        tags:
            - { name: liip_monitor.check, alias: elasticsearch }
