parameters:
    bangpound_phirehose.stream.class: Bangpound\PhirehoseBundle\Stream\BasicStream
    bangpound_phirehose.follow: []
    bangpound_phirehose.track: []
    bangpound_phirehose.locations: []
    bangpound_phirehose.count: null

services:
    bangpound_phirehose.stream:
        class: %bangpound_phirehose.stream.class%
        arguments:
            - %bangpound_phirehose.oauth_token%
            - %bangpound_phirehose.oauth_secret%
            - "@=constant('Phirehose::METHOD_FILTER')"
            - "@=constant('Phirehose::FORMAT_JSON')"
        calls:
            - [setFollow, [%bangpound_phirehose.follow%]]
            - [setTrack, [%bangpound_phirehose.track%]]
            - [setLocations, [%bangpound_phirehose.locations%]]
            - [setCount, [%bangpound_phirehose.count%]]
            - [setDispatcher, ['@event_dispatcher']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setLogger, ['@logger']]
        properties:
            consumerKey: %bangpound_phirehose.twitter_consumer_key%
            consumerSecret: %bangpound_phirehose.twitter_consumer_secret%
        tags:
            - { name: monolog.logger, channel: phirehose }

    bangpound_phirehose.logger.processor.memory_peak_usage:
        class: Monolog\Processor\MemoryPeakUsageProcessor
        tags:
            - { name: monolog.processor, channel: phirehose }

    bangpound_phirehose.logger.processor.memory_usage:
        class: Monolog\Processor\MemoryUsageProcessor
        tags:
            - { name: monolog.processor, channel: phirehose }
