parameters:
    rshief_pubsub.notification_listener.class: Rshief\PubsubBundle\EventListener\PubsubNotification
    rshief_pubsub.form.type.hub_name.class: Rshief\PubsubBundle\Form\Type\HubNameType
    rshief_pubsub.guzzle.plugin.accept_json.class: Rshief\PubsubBundle\Guzzle\Plugin\AcceptJson

services:
    hub.superfeedr:
        class: Sputnik\Bundle\PubsubBundle\Hub\SuperfeedrHub
        arguments: [ superfeedr, http://superfeedr.com/hubbub, %superfeedr_user%, %superfeedr_password% ]
        tags:
            - { name: sputnik_pubsub.hub }

    hub.blogger:
        class: Sputnik\Bundle\PubsubBundle\Hub\Hub
        arguments: [ blogger, http://pubsubhubbub.appspot.com ]
        tags:
            - { name: sputnik_pubsub.hub }

    hub.tumblr:
        class: Sputnik\Bundle\PubsubBundle\Hub\Hub
        arguments: [ tumblr, http://tumblr.superfeedr.com ]
        tags:
            - { name: sputnik_pubsub.hub }

    rshief_pubsub.notification_listener:
        arguments: [ "@sonata.notification.backend" ]
        class: %rshief_pubsub.notification_listener.class%
        tags:
            - { name: kernel.event_subscriber }

    rshief_pubsub.form.type.hub_name:
        class: %rshief_pubsub.form.type.hub_name.class%
        arguments:
            - "@sputnik_pubsub.hub_provider"
        tags:
            - { name: form.type, alias: hub_name }
