parameters:
    bangpound_castle.types:
        Bangpound.Bundle.TwitterStreamingBundle.CouchDocument.AtomEntry: "kal3a: Twitter"
        Rshief.MigrationBundle.CouchDocument.CollectorAtomEntry: Twitterminer
        Rshief.MigrationBundle.CouchDocument.AtomEntry: VBulletin
        Bangpound.Bundle.CastleBundle.CouchDocument.AtomEntry: Castle
        Bangpound.Bundle.PubsubBundle.CouchDocument.AtomEntry: "kal3a: RSS / Atom"

    bangpound_castle.types.lower:
        bangpound.bundle.twitterstreamingbundle.couchdocument.atomentry: "kal3a: Twitter"
        rshief.migrationbundle.couchdocument.collectoratomentry: Twitterminer
        rshief.migrationbundle.couchdocument.atomentry: VBulletin
        bangpound.bundle.castlebundle.couchdocument.atomentry: Castle
        bangpound.bundle.pubsubbundle.couchdocument.atomentry: "kal3a: RSS / Atom"

    bangpound_castle.command.export.class: Bangpound\Bundle\CastleBundle\Command\ExportCommand
    bangpound_castle.command.prune.class: Bangpound\Bundle\CastleBundle\Command\PruneCommand
    bangpound_castle.command.update_view.class: Bangpound\Bundle\CastleBundle\Command\UpdateViewCommand

services:
    bangpound_castle.normalizer.couchdb:
        class: Bangpound\Bundle\CastleBundle\Serializer\CouchDbNormalizer
        tags:
            - { name: serializer.normalizer }

    bangpound_castle.normalizer.couchdb_attachment:
        class: Bangpound\Bundle\CastleBundle\Serializer\AttachmentNormalizer
        tags:
            - { name: serializer.normalizer }

    bangpound_castle.command.export:
        class: %bangpound_castle.command.export.class%
        calls:
            - [ setRegistry, [ "@doctrine_couchdb" ] ]
        tags:
            - { name: console.command }

    bangpound_castle.command.prune:
        class: %bangpound_castle.command.prune.class%
        calls:
            - [ setRegistry, [ "@doctrine_couchdb" ] ]
        tags:
            - { name: console.command }

    bangpound_castle.command.update_view:
        class: %bangpound_castle.command.update_view.class%
        calls:
            - [ setRegistry, [ "@doctrine_couchdb" ] ]
        tags:
            - { name: console.command }

    bangpound_castle.process.elasticsearch:
        class: Bangpound\Bundle\InvokerBundle\Process\ProcessBuilder
        arguments: [ ["/usr/local/bin/elasticsearch", "--config=/usr/local/opt/elasticsearch/config/elasticsearch.yml"] ]
        calls:
            - [ setTimeout, [ ~ ]]
        tags:
            - { name: bangpound_invoker.server }

    bangpound_castle.process.couchdb:
        class: Bangpound\Bundle\InvokerBundle\Process\ProcessBuilder
        arguments: [ ["couchdb" ] ]
        calls:
            - [ setTimeout, [ ~ ]]
        tags:
            - { name: bangpound_invoker.server }

    bangpound_castle.process.rabbitmq:
        class: Bangpound\Bundle\InvokerBundle\Process\ProcessBuilder
        arguments: [ ["rabbitmq-server"] ]
        calls:
            - [ setTimeout, [ ~ ]]
        tags:
            - { name: bangpound_invoker.server }
