services:
    nab3a.console.application:
        class: AppBundle\Console\Application
        arguments:
            - 'nab3a'
            - '@@package_version@'
        calls:
            - [ setDispatcher, [ '@event_dispatcher' ] ]

    nab3a.console.command:
        abstract: true
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: monolog.logger }

    nab3a.console.input:
        class: Symfony\Component\Console\Input\ArgvInput

    nab3a.console.output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    nab3a.console.logger_helper:
        class: AppBundle\Console\LoggerHelper
        arguments: ['@=service(''nab3a.console.output'').getErrorOutput()']
        calls:
            - [ setContainer, ['@service_container'] ]
