parameters:
    nab3a.twitter.output.pattern: 'data/{user.screen_name}/{created_at.date}/{id}.json'
    nab3a.twitter.batch_output.pattern: 'data/{id}.json'

services:
    nab3a.twitter.request_factory:
        class: AppBundle\Stream\RequestFactory
        arguments: [ { delimited: length } ]

    AppBundle\Stream\RequestFactory: '@nab3a.twitter.request_factory'

    nab3a.twitter.guzzle.middleware.retry:
        parent: nab3a.guzzle.middleware.retry
        tags:
            - { name: guzzle.middleware, client: nab3a.twitter.guzzle.client, middleware_name: retry }

