parameters:
    rshief_kal3a.command.populate_stats: Rshief\Bundle\Kal3aBundle\Command\PopulateStatsCommand

services:
    rshief_kal3a.command.populate_stats:
        class: %rshief_kal3a.command.populate_stats%
        tags:
            -  { name: console.command }
