parameters:
    rshief_kal3a.command.populate_stats.class: Rshief\Bundle\Kal3aBundle\Command\PopulateStatsCommand
    rshief_kal3a.command.populate_trends.class: Rshief\Bundle\Kal3aBundle\Command\PopulateTrendsCommand
    rshief_kal3a.command.copy_trends.class: Rshief\Bundle\Kal3aBundle\Command\CopyTrendsCommand
    rshief_kal3a.command.calculate_trends.class: Rshief\Bundle\Kal3aBundle\Command\CalculateTrendsCommand

services:
    rshief_kal3a.command.populate_stats:
        class: %rshief_kal3a.command.populate_stats.class%
        tags:
            -  { name: console.command }

    rshief_kal3a.command.populate_trends:
        class: %rshief_kal3a.command.populate_trends.class%
        tags:
            -  { name: console.command }

    rshief_kal3a.command.copy_trends:
        class: %rshief_kal3a.command.copy_trends.class%
        tags:
            -  { name: console.command }

    rshief_kal3a.command.calculate_trends:
        class: %rshief_kal3a.command.calculate_trends.class%
        tags:
            -  { name: console.command }
