parameters:
#    rshief_kal3a.example.class: Rshief\Bundle\Kal3aBundle\Example

services:
#    rshief_kal3a.example:
#        class: %rshief_kal3a.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
